name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load cached modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Load Node.js latest
        uses: actions/setup-node@v2-beta
        with:
          node-version: '20.x'

      - name: Install all dependencies
        run: npm ci

      - name: Compile TypeScript and build Library files
        run: npm run build

  lint:
    name: lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Use Node.js latest
        uses: actions/setup-node@v2-beta
        with:
          node-version: '20.x'

      - name: Get cached modules
        uses: actions/cache@v3.3.3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run ESLint
        run: npm run lint
