name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Load Node.js latest
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '20.x'

      - name: Load cached modules
        uses: actions/cache/save@v3.3.3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install all dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
  build:
    name: build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '20.x'

      - uses: actions/cache@v3.3.3
        with:
          path: |
            **/node_modules
            **/lib
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - run: npm run build
  test:
    name: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '20.x'

      - uses: actions/cache/restore@v3.3.3
        with:
          path: |
            **/node_modules
            **/lib
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Test
        run: npm run test:nobuild
